### ISSUE TITLE
Question with warning when installing add-on 

### ISSUE THREAD

**Issue by annworley** [dkoudela/controlled-pm-for-confluence#2]
Hi, Ann here, from Atlassian's online Community forum. A customer asked a question about the message that comes up when you install Controlled PM in Cloud:

> Controlled Project Management may store your data on David Koudela Inc.'s server so it can integrate with your Confluence instance.

The link to the data security and privacy statement just went to the user manual.

Please answer the customer's question on our forum:
https://community.atlassian.com/t5/Product-Apps-questions/Question-with-warning-when-installing-add-on/qaq-p/654625

Thanks very much!
Ann

**Comment by dkoudela** [comment]
Hi,

The documentation has been updated to reflect the actual Data Security and Privacy Statement:
https://github.com/dkoudela/controlled-pm-for-confluence/wiki/Data-Security-and-Privacy-Statement

Best Regards,
David.
