### ISSUE TITLE
FAQ Template

### ISSUE THREAD

**Issue by bhavinacharya** [dkoudela/controlled-pm-for-confluence#3]
Hi,
I am using your templates but require FAQ template for my Technical Support Team where they can find issues very easily to provide support to customer.
YOur reply would be a great help for me.
Thanks in advance.
Bhavin Acharya.

**Comment by dkoudela** [comment]
Hi Bhavin Acharya,
The templates are based on PRINCE2 project management method.
They mirror basis of all the documents required for PRINCE2 methodology.
Unfortunately, FAQ document is not part of PRINCE2.
Best Regards,
David.

**Comment by bhavinacharya** [comment]
Ok thanks.
